F1rrel/RenewedVillageGrowth

cargo.nut

Changed the foreach loop to for loop with decreasing the index after each removed cargo id.

fixed removing unused cargo ids

---

cargo.nut
info.nut

Updated FIRS to version 4 alpha 4
- Steeltown - removed Rebar and Petroleum Fuels, added Potash
- In A Hot Country - added (same as FIRS 3)

Updated to FIRS 4 alpha 4

---

main.nut

Closes #6 
Added [toylib ](https://www.tt-forums.net/viewtopic.php?f=65&t=71597)and scplib to allow toy AIs to live. Maybe it can lead to something interesting...

Added toylib and scplib

---

changelog.txt
version.nut

Bump to 5.0

---

cargo.nut
info.nut
lang/english.txt
main.nut
make_tar.py
story.nut

- modified: The supported economy is automatically detected from the cargo list

automatic_categories

---

industry.nut

When a NewGRF disallows prospecting an industry, the `GSIndustryType.ProspectIndustry()` still returns true and it gets stuck on the one industry type. This MR will check if the number of industries was increased after funding, otherwise ignores building that industry type.

Fixed prospecting when an industry is disallowed by newGRF

---

industry.nut

Fixed industry randomization for zero 1 cargo accepting industries

---

cargo.nut

Ignore CZTR cargo LVPT

---

cargo.nut
company.nut
industry.nut
info.nut
license.txt
main.nut
readme.txt
story.nut
strings.nut
town.nut

Converted tabs to spaces with 4 spaces per tab. Removed trailing whitespaces.

Code formatting

---

README.md
changelog.txt
info.nut
lang.txt
readme.txt
version.nut

Bump to 6.1

---

README.md
changelog.txt
lang.txt
lang/simplified_chinese.txt
lang_files/simplified_chinese.txt
readme.txt
version.nut

Bump to 6.2

---

lang/english.txt
town.nut

Display accumulated cargo per category
Equalize categories impact on growth

Changes to supplied and stockpiled cargo

---

lang.txt
lang/czech.txt
lang/english.txt
lang/french.txt
lang/simplified_chinese.txt
lang/slovak.txt
lang_files/simplified_chinese.txt

- english
- slovak
- czech
- french
- simplified chinese

Updated lokalizations

---

README.md
changelog.txt
lang.txt
lang_files/simplified_chinese.txt
readme.txt
version.nut

Bump to 7.0

---

lang/polish.txt

Translated game script to Polish language

Added polish translation

---

lang/english.txt

Found some typos while working on adding compatibility for my new industry set. 😃

Fix: Typo in english.txt

---

cargo.nut

OTIS 03 support

---

cargo.nut

Fixed min pop demand below 5 categories.

Fix: Min pop demand below 5 categories

---

cargo.nut
info.nut
main.nut
readme.txt
town.nut

New randomization types Ascending and Descending. The number of cargos chosen for each category is either ascending or descending.

New: Randomization ascending and descending

---

cargo.nut
lang/english.txt

Added support for Wannaroo Basic Industries (WRBI) 1200.

New: Added WRBI 1200

---

README.md
changelog.txt
info.nut
lang.txt
lang/czech.txt
lang/french.txt
lang/polish.txt
lang/simplified_chinese.txt
lang/slovak.txt
lang_files/simplified_chinese.txt
readme.txt
version.nut

Bump to 8.0

---

town.nut

Fix missing condition for industry descending randomization which lead to rewriting cargo hash.

Fix: Industry descending loading

---

README.md
changelog.txt
lang.txt
readme.txt
version.nut

Bump to 8.1

---

info.nut

Adjusted limits of some GS settings to give more freedom in tuning the GS.
Closes #100

Change: Adjusted limits of some GS settings

---

cargo.nut
lang/english.txt

Added Real Industries Beta made by Temporal8: https://www.tt-forums.net/viewtopic.php?p=1254290#p1254290

Add: Real Industries Beta

---

README.md
changelog.txt
lang.txt
readme.txt
version.nut

Bump to 8.2

---

lang/german.txt

German translation by pankratz.

Add: German Translation

---

README.md
changelog.txt
lang.txt
readme.txt
version.nut

Bump to 9.0

---

lang/japanese.txt

Hello,
Here’s a Japanese translation for RVG, tested on OpenTTD 13.0, and reviewed by a native speaker.
Best regards.

Add Japanese translation

---

lang/french.txt

Hi, I added some missing strings in the French translation file.
The script should now be fully translated in french, except for the settings — which as I understand cannot be translated for game scripts.
I also slightly adjusted a few strings in a second commit because they seemed weird to read in hindsight. All seems well when playing with my fork of the script!

Updated french translation

---

lang/czech.txt
lang/slovak.txt

Added missing Welcome screen strings and Server rules strings.

Change: Updated slovak and czech translations

---

changelog.txt
readme.txt
version.nut

Bump to 9.2

---

cargo.nut

OTIS 05 support
Changes :
Cargolabel NICK to NKOR
Cargolabel SASH to FICR

Fix : OTIS 05 support

---

README.md
changelog.txt
readme.txt
version.nut

Version 9.3

---

lang/russian.txt

Full translation. Perhaps in some places it is not entirely correct. But it's better than the current

Russian translation

---

README.md
changelog.txt
readme.txt
version.nut

Version 10.0

---

README.md
changelog.txt
readme.txt
version.nut

Bump to 10.1

---

README.md
changelog.txt
lang/czech.txt
lang/french.txt
lang/slovak.txt
readme.txt
version.nut

Bump to 11.0

---

README.md
cargo.nut
changelog.txt
readme.txt
version.nut

Bump to 12.0

---

lang/ukrainian.txt

Hi,
Please accept Ukrainian translation.
Tested locally, script works well.

Ukrainian translation

---

README.md
changelog.txt
readme.txt
version.nut

Bump to 12.1
