F1rrel/RenewedVillageGrowth

- main.nut
- town.nut
Closes #7 
Fixed integer overflow when saving cargo hash. Cargo hash has 64 bits and squirrel uses 64 bit integers. But saving data only uses 32 bit integers. The value is casted into 64 bit integer and if the value overflew into negative numbers, the bits 32-63 are all ones, changing the result value. So to maintain the same value after loading, it is necessary to split the number into upper and lower part and convert it to integer range before saving. When loading, the value is converted back into unsigned int range.
Added randomization of random seed at the start of the script.
> fixed invalid cargo ids and random seed

- cargo.nut
- lang/english.txt
- main.nut
- story.nut
- strings.nut
**Added algorith for creating default cargo categories:**
- now all industry NewGRF types are supported
- the cargo types are divided into raw and other (based on industry type that produces the cargo type)
- if there are more than 10 cargo types in the type (raw/other), it will create two categories, otherwise it will be one category
- for two categories per type, the cargo types are devided randomly equally between these categories
- allows for creating 3, 4, 5 number of categories based on number of cargo types
- first category is allways PASS (0) and MAIL (2)
Closes #5
> Default cargo categories

- industry.nut
- info.nut
- main.nut
Maintain at least a set number of raw industries on the map:
- executed during initialization and every year
- prospects raw industries on the map so that there are same numbers of each industry type
- the number of industries uses OpenTTD industry density values (number of raw industries that would be expected to be built during world generation on that map size)
- allows for creating maps with only raw industries
> Implemented industry stabilizer

- info.nut
- main.nut
- town.nut
Allow changing all GS settings:
- all settings have flag CONFIG_INGAME
- changing `randomization` and `use_town_sign` in a running game will be ignored
> Allow changing all GS settings

- strings.nut
Prevents cluttering the town box with too many cargos. It is still possible  to display it with `Combined` or `Full cargo list` display options.
> Dont display all cargos when randomization is none

- lang/english.txt
- main.nut
- story.nut
- version.nut
Saving can take up to 100000 opcodes, so there is finite number of towns the GS can save. (currently 1500 with 65 opcodes per town) When there are more towns than the limit, a warning is issued and the GS is disabled.
> Issue warning for too many towns to save

- industry.nut
- info.nut
- main.nut
- story.nut
- strings.nut
- town.nut
There are now two choices of industry randomization: ascending (more cargo types in higher categories) and descending.
> Random industry descending

- town.nut
The growth rate is limited to 1 day minimum so there is no expoding growth of towns, which could be achieved by using very easy parameters.
> fixed zero growth rate

- town.nut
The calculated town growth rate could go into negative numbers when the goal diff was below 50%. Better limiting of minimal and maximal town growth rate.
> fix tgr for goal diff < 50%

- town.nut
Fix to [bug report ](https://www.tt-forums.net/viewtopic.php?p=1242221#p1242221).
The cargo label was used instead of cargo id to stop cargo monitoring.
> fixed stopping monitoring of towns

- lang/simplified_chinese.txt
- lang_files/simplified_chinese.txt
Added simplified chinese lang file from #51 thanks to @SuperCirno.
There are a few things missing, could you please look into them @SuperCirno ?
There is a string translation missing:
```
To achieve requirements for a category, you can deliver any cargo belonging to it.
:
```
There is a `{STRING}` identifier missing in the translation:
```
Each town has a selection of {STRING} from each category. To achieve requirements for a category, you can deliver any cargo that the Town requires for that category as shown in the Town info window.
:为了达到某个类别的要求.您可以交付任何属于该类别的货物
```
> simplified chinese

- cargo.nut
Resolves #54 
FIRS 4.2.x changed Wood to Logs. Even thou the cargo label stayed the same, the order of the cargo types changed, which made it incompatible with the previous versions. The change affects FIRS4__ARCTIC_BASIC and FIRS4__IN_A_HOT_COUNTRY.
> Updated FIRS to 4.3.0

- cargo.nut
YETI workers are not a good cargo type to limit town growth.
> Removed limiter workers from YETI

- info.nut
- readme.txt
- town.nut
Calculates new town growth rate based on missing cargo percentage.  
Firstly a maximum growth rate for the town is calculated with g_factor being the growth rate at 0 population. The growth rate is faster the bigger the town is. The decline is slow enought to have reasonable growth rate even for bigger towns.
An exponential extra growth is calculated based on missing cargo requirements. The extra growth rate factor is multiplied by the difference between lowest TGR and maximum TGR to get extra growth rate in days. The effect of missing cargo decreases with higher fulfillment, but is still significant. 
The resulting growth rate is the combination of both factors, the max growth rate and the extra growth rate.
> New growth rate calculation

- cargo.nut
fixes #70 
Mistake of using `+` sign instead of `|` when building binary hash of cargos, so overflow into negative numbers (squirrel uses int64, not uint64) lead to wrong result.
> Fix: Cargo hash calculation

- cargo.nut
Removed duplicated PLAS (produced by bulk terminal so should be imported goods, but was both imported goods and processed materials)
Moved duplicated PIPE from final products to processed materials
> Fixes in FIRS4 Steeltowns cargoes

- info.nut
- readme.txt
- town.nut
Changed parameter "minimum missing percentage for TGR growth" to "minimum fulfilled percentage for TGR growth". Now 30 means the categories have to be fulfilled at least to 30% (with 3 categories, it is enough to fully supply one category).
Closes https://github.com/F1rrel/RenewedVillageGrowth/issues/75
> Fix: Minimum fulfilled percentage for TGR growth

- cargo.nut
- info.nut
- main.nut
- readme.txt
- story.nut
- strings.nut
- town.nut
Added new settings:
"category_X_min_pop": change the minimum population at which the demand for that category starts. The categories are sorted based on selected values. Choosing value 0 uses the economy's default value.
"allow_0_days_growth": the town growth rate can go to zero.
> New: added category and zero growth settings

- cargo.nut
- industry.nut
- lang/english.txt
- main.nut
- story.nut
Also compare cargo list length with economy cargo list length to prevent choosing economy with matching beginning of the cargo list.
Added support of min pop demand options for industry randomization. Only the min pop demand values are changed, the categories are not sorted.
Better handling of warnings that cause the GS to stop. Handles also incorrect creation of cargo list and industry list.
> Fix: Cargo and industry lists

- cargo.nut
- company.nut
- lang/english.txt
- story.nut
New custom story page. Useful for example for server rules and other custom information. Change texts in the `lang/english.txt` to enable the custom story page. Add custom texts between `STR_SB_CUSTOM_TITLE` and `STR_SB_CUSTOM_END`, which will be added to the new page. If there is no text between them, the custom page is not created. `STR_SB_CUSTOM_WELCOME` is shown in the welcome page and points to the new custom page. `STR_SB_CUSTOM_TITLE` changes title of the custom page.
Example of a custom story page:
```
STR_SB_CUSTOM_WELCOME       :Please find the server rules in the {ORANGE}{STRING} story book page{BLACK}.
STR_SB_CUSTOM_TITLE         :Server rules
STR_SB_CUSTOM_1             :Rule 1
STR_SB_CUSTOM_2             :Rule 2
STR_SB_CUSTOM_END           
```
| Welcome story page      | …
> New: Custom story page

- story.nut
Fix that cargo story page is global, so does not need creating for each company.
> Fix: Cargo story page is global

- cargo.nut
Per our discussion on Discord, this should check the correct index when using ECS Industries.
Closes #92.
Note: I have not tested with ECS Industries, but it does prevent a crash when using other industry NewGRFs.
> Fix: Check the correct index for ECS cargos

- cargo.nut
- lang/english.txt
This adds compatibility for my latest industry set, a complete rework of Improved Town Industries with different cargos and mechanics.
I've added it as a new economy rather than overwriting ITI 1.x, in case people end up playing the old version.
It's ready for merge and release, as ITI 2.0 is finished and ready for release itself as soon as a new version of RVG is published.
> Add: Improved Town Industries v2

- company.nut
- industry.nut
- main.nut
- town.nut
Pause in single player and multiplayer acts differently. Also some commands require different minimum command pause level to be allowed. In single player the command pause level can be adjusted by GS, but in multiplayer, it is disallowed.
This PR handles industry funding, Goal GUI creation, town growth rate setting and town text box creation in all types of command pause levels in both SP and MP. In SP, the command pause level is changed if needed and reset to previous value. In MP, the initialization of conflicting parts waits for the game to unpause.
Closes #90
> Fix: Handle commands that require specific command pause level

- cargo.nut
Hello!
I went through XIS economy, and found some weird assignments of categories. There is my proposition of changes:
[4 - AORE/bauxite]: it's definitely raw material digged in bauxite mine, so it should be raw instead of processed one.
[11 - FOOD/food]: it's in final products, but due to gameplay it would be better to keep it in food category (can be delivered to hotels in cities, and there are not so many raw food category cargoes)
[20 - BOOM/explosives]: now it's final product, but it's used to create engineering supplies and created from other materials, so moving to processed material
[22 - FERT/fertiliser]: as above, but used for farm supplies
[43 - FICR/plant_fibres]: it's in raw food, but it's used only for creating technical things, so moving to raw materials
[48 - SALT/salt]: …
> Updated cargoes in XIS economy

- cargo.nut
- industry.nut
- info.nut
- main.nut
- strings.nut
- town.nut
This feature is used to specify the probability of choosing a nearby cargo type / industry type instead of a random one. Added new parameter `Randomization: Probability to use nearby cargo types [%]`, which specifies the % chance of chosing nearby compared to random cargo type.
Cargo randomization:
For each town, a list of nearest industries is created. From these industries, a cargo list is created for each cargo category based on used economy. These cargo lists specify which cargo types are near that town and to which category they belong. When randomizing cargo categories, based on the probability parameter, cargo from near cargo types is chosen compared to random cargo type. If there are no near cargo types for that category, random cargo type is chosen.
Industry randomization:
For …
> Add: Probability to use nearby cargo types

- cargo.nut
- main.nut
When there were more then 10 of raw or processed cargo types, they were split in two cargo categories. The splitting was using randomization, which caused changing cargo categories after starting/loading the game. Fixed it by a deterministic 1/1 split.
> Fix: Changing cargo categories in procedural generation

- lang/english.txt
- story.nut
STR_SB_WELCOME_LIMIT_GROWTH must use {STRING1} instead of {STRING} because STR_SB_WELCOME_LIMIT_GROWTH_DELAY consumes one parameter.
For the case when the extra string is omitted, I introduced a trivial STR_STRING string for the sake of consuming one extra parameter.
Tested on both OpenTTD 13.0 and nightly, with and without limiter_delay.
Fix #114.
> Fix STR_SB_WELCOME_LIMIT_GROWTH_DELAY substitution

- cargo.nut
`GSIndustryList_CargoProducing` only returns Industries that are present in the map, so when an industry type is missing in the map, a cargo can be wrongly categorized. This could cause mixing of cargo types in categories when the missing industry type is added. Using `GSIndustryTypeList` is safe for stable raw cargo categorization.
> Fix is raw cargo

- industry.nut
When selecting next industry for funding, when all industries were processing or ignored, it would return index 0, which could cause trying to fund industry with index 0 in a never ending loop. Fixed by checking if the list of valid industries for funding is empty.
> Fix: Funding failed continuously when no industry could be funded

- cargo.nut
- lang/english.txt
This PR adds the latest version of Pikka's Industry Redux set currently available on BaNaNaS, known as PIRS 2022.
I discussed cargo categories with Pikka and got their agreement. Population requirements and decay rates are untested but follow other industry sets.
> Add: Pikka's Industry Redux Set (PIRS 2022)

- info.nut
- subsidies.nut
In the GS configuration window, the dropdown window to select subsidy types misspells "Passenger" as "Passanger".
This PR fixes this string typo, as well as the enum.
> Fix: Misspelling of "Passenger" in subsidy type setting

- industry.nut
The existing implementation has worse than O(N) behaviour and churns a lot of memory while doing it, which makes for a long delay on large maps.
`GSTile.GetClosestTown` already solves this problem in an efficient way.
> Codechange: Improve performance of GetNearbyIndustriesToTowns

- info.nut
- main.nut
- town.nut
- version.nut
With the fix of saving int64 in https://github.com/OpenTTD/OpenTTD/pull/9415, the saving and loading town functions could be optimized to not split `limit_transported` and `cargo_hash` into two int32 variables. With this change, the per town saving opcodes were reduced from 65 to 49, which allows to save 2000 towns. API version was increased to 12, where this int64 saving was fixed.
> Change: Optimized save/load functions

- town.nut
When a scenario is started, the GS is initialized with the current towns. If the savegame is converted back to a scenario and new towns are added, the GS tries to load them, but they are not in the save data, which breaks the GS. Solved by checking if the town index exists in the save data, and if not, initialize the town.
> Fix: Adding towns in scenario editor

- cargo.nut
- info.nut
- main.nut
Added 6th category to FIRS4/5 Steeltown. Refactored AXIS Steeltown. This can be enabled (it is by default) using "Cargo: Use 6 cargo categories for supported economies" parameter.
> Feat: Added 6th category to some economies

- main.nut
GSToyLib stopped working since OpenTTD 12 due to API changes. This uses fixed version [GSToyLib v2](https://bananas.openttd.org/package/game-script-library/544c4753).
> Fix: Use updated GSToyLib v2

- cargo.nut
- lang/english.txt
- version.nut
This adds support for the AXIS Tropical Paradise economy. I basically just copied #147. Please double check the changes cause I have only done a tiny bit with OpenTTD scripts before. I tested it on OpenTTD 14.1 and JGR 63 with the 5 category mode and 6 category modes
Here are the cargo categories (6 category mode):
5 category mode (raw food & raw materials combined):
storybook:
> Added AXIS Tropical Paradise economy with 2 modes
